package com.eikona.mata.service.impl;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.stereotype.Service;

import com.eikona.mata.constants.ApplicationConstants;
import com.eikona.mata.constants.DailyAttendanceConstants;
import com.eikona.mata.constants.NumberConstants;
import com.eikona.mata.dto.PaginationDto;
import com.eikona.mata.entity.DailyReport;
import com.eikona.mata.entity.Transaction;
import com.eikona.mata.repository.DailyAttendanceRepository;
import com.eikona.mata.repository.TransactionRepository;
import com.eikona.mata.service.DailyAttendanceService;
import com.eikona.mata.util.CalendarUtil;
import com.eikona.mata.util.GeneralSpecificationUtil;

@Service
@EnableScheduling
public class DailyAttendanceServiceImpl implements DailyAttendanceService{

	@Autowired
	private DailyAttendanceRepository dailyAttendanceRepository;

	@Autowired
	private GeneralSpecificationUtil<DailyReport> generalSpecificationDailyAttendance;
	
	@Autowired
	private TransactionRepository transactionRepository;
	
	@Autowired
	private CalendarUtil calendarUtil;
	
	@Value("${dailyreport.autogenerate.enabled}")
	private String enableGenerate;
	
//	@Scheduled(cron ="0 0 9 * * *")
	public void autoGenerateDailyReport() {
		
		if("Yes".equalsIgnoreCase(enableGenerate)) {
			SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
			Date yesterday=calendarUtil.getPreviousDate(new Date(), -1, 0, 0,0);
			String date=inputFormat.format(yesterday);
			generateDailyAttendance(date,date);
		}
		
	}
	
	@SuppressWarnings("deprecation")
	public List<DailyReport> generateDailyAttendance(String sDate, String eDate) {

		List<DailyReport> dailyReportList = new ArrayList<>();
		try {
			
			SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
			SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
			DateFormat timeFormat = new SimpleDateFormat(ApplicationConstants.TIME_FORMAT_24HR);
			sDate = format.format(inputFormat.parse(sDate));
			eDate = format.format(inputFormat.parse(eDate));
			
			Date startDate = calendarUtil.getConvertedDate(format.parse(sDate), 00, 00, 00);
			Date endDate = calendarUtil.getConvertedDate(format.parse(eDate), 23, 59, 59);
	
			List<Transaction> transactionList = transactionRepository.getTransactionData(startDate,endDate);
			
			List<DailyReport> dailyAttList = dailyAttendanceRepository.findByDateAndOrganization(startDate,endDate);

			Map<String, DailyReport> existingReportMap = new HashMap<String, DailyReport>();
			
			for (DailyReport dailyReport : dailyAttList) {
				String key = dailyReport.getEmpId() + "-" + dailyReport.getDateStr();
				key = key.trim();
				existingReportMap.put(key, dailyReport);
			}
			
			Map<String, DailyReport> reportMap = new HashMap<String, DailyReport>();

			for (Transaction transaction : transactionList) {
	
				try {
					
					String key = transaction.getEmpId() + "-" + transaction.getPunchDateStr();
					key = key.trim();
					DailyReport dailyReport = null;
					
					Date currDate = format.parse(transaction.getPunchDateStr());
					if(transaction.getPunchDate().getHours() < 9) {
						
						Calendar currDateCal = Calendar.getInstance();
						currDateCal.setTime(currDate);
						currDateCal.add(Calendar.DAY_OF_MONTH, -1);
						currDate = currDateCal.getTime();
						
						DailyReport dailyReportYesterday = dailyAttendanceRepository.findByEmpIdAndDate(transaction.getEmpId().trim(),currDate);
						
						if(null!=dailyReportYesterday) {
							if(Integer.parseInt(dailyReportYesterday.getEmpInTime().split(":")[0]) < 17) {
								currDate = format.parse(transaction.getPunchDateStr());
							}else {
								key = dailyReportYesterday.getEmpId() + "-" + dailyReportYesterday.getDateStr();
								key = key.trim();
								if(!existingReportMap.containsKey(key)) {
									existingReportMap.put(key, dailyReportYesterday);
								}
							}
						}
					}
					
					if(existingReportMap.containsKey(key)) {
						reportMap.put(key, existingReportMap.get(key));
					}
					
					if(!reportMap.containsKey(key)) {
						
						dailyReport = new DailyReport();
						dailyReport.setEmpId(transaction.getEmpId().trim());
						dailyReport.setDateStr(transaction.getPunchDateStr());
						dailyReport.setDate(format.parse(transaction.getPunchDateStr()));
						dailyReport.setEmployeeName(transaction.getName());
						dailyReport.setDepartment(transaction.getDepartment());
						dailyReport.setMissedOutPunch(true);
						dailyReport.setEmpInTime(transaction.getPunchTimeStr());
						dailyReport.setEmpInLocation(transaction.getDeviceName());
						dailyReport.setAttendanceStatus("Present");
						if(Integer.parseInt(dailyReport.getEmpInTime().split(":")[0])>=17) 
							dailyReport.setShift("N");
						
							reportMap.put(key, dailyReport);
						} else {
							
							dailyReport = reportMap.get(key);
							if (dailyReport.getEmpInTime().equalsIgnoreCase(transaction.getPunchTimeStr())) {
								continue;
							} else {
								
								dailyReport.setEmpOutTime(transaction.getPunchTimeStr());
								dailyReport.setEmpOutLocation(transaction.getDeviceName());
		
								dailyReport.setMissedOutPunch(false);
		
								LocalTime empIn = LocalTime.parse(dailyReport.getEmpInTime());
								LocalTime empOut = LocalTime.parse(dailyReport.getEmpOutTime());
		
								
		
								Long workHours = empIn.until(empOut, ChronoUnit.HOURS);
								Long workMinutes = empIn.until(empOut, ChronoUnit.MINUTES);
								
								if(workHours<0) {
									workHours = 24 + workHours;
									workMinutes = 60 + workMinutes;
								}
								
		
								dailyReport.setWorkTime(String.valueOf(workHours) + ":" + String.valueOf(workMinutes % 60));
								
								if("N".equalsIgnoreCase(dailyReport.getShift()) && (Integer.parseInt(dailyReport.getEmpOutTime().split(":")[0])<=9)) {
									Long tillMidNight=empIn.until(LocalTime.parse("23:59:59"), ChronoUnit.MINUTES);
									Long afterMidNight=LocalTime.parse("00:00:00").until(empOut, ChronoUnit.MINUTES);
									workMinutes =tillMidNight+afterMidNight;
									dailyReport.setWorkTime(String.valueOf(workMinutes/60) + ":" + String.valueOf(workMinutes % 60));
								} 
								
								reportMap.put(key, dailyReport);
						}
					}
				} catch (ParseException e) {
					e.printStackTrace();
				}
			}
		
			Set<String> keySet =  reportMap.keySet();
			for (String string : keySet) {
				dailyAttList.add(reportMap.get(string));
			}
			dailyAttendanceRepository.saveAll(dailyAttList);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return dailyReportList;
	}


	@Override
	public PaginationDto<DailyReport> searchByField(String sDate, String eDate, String employeeId,String employeeName,String department, String status, int pageno,String sortField, String sortDir) {

		Date startDate = null;
		Date endDate = null;
		if (!sDate.isEmpty() && !eDate.isEmpty()) {
			SimpleDateFormat format = new SimpleDateFormat(ApplicationConstants.DATE_FORMAT_OF_US);
			try {
				startDate = format.parse(sDate);
				endDate = format.parse(eDate);
				
				endDate = calendarUtil.getConvertedDate(endDate, NumberConstants.TWENTY_THREE, NumberConstants.FIFTY_NINE, NumberConstants.FIFTY_NINE);
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		if (null == sortDir || sortDir.isEmpty()) {
			sortDir = ApplicationConstants.ASC;
		}
		if (null == sortField || sortField.isEmpty()) {
			sortField = ApplicationConstants.ID;
		}
		
		
		
		Page<DailyReport> page = getDailyAttendancePage( employeeId, employeeName, department,
				pageno, sortField, sortDir, startDate, endDate, status);
		List<DailyReport> employeeShiftList = page.getContent();

		sortDir = (ApplicationConstants.ASC.equalsIgnoreCase(sortDir)) ? ApplicationConstants.DESC : ApplicationConstants.ASC;
		PaginationDto<DailyReport> dtoList = new PaginationDto<DailyReport>(employeeShiftList,
				page.getTotalPages(), page.getNumber() + NumberConstants.ONE, page.getSize(), page.getTotalElements(),
				page.getTotalElements(), sortDir, ApplicationConstants.SUCCESS, ApplicationConstants.MSG_TYPE_S);
		return dtoList;
	}
	
	private Page<DailyReport> getDailyAttendancePage(String employeeId, String employeeName,
			String department,  int pageno, String sortField, String sortDir, Date startDate,
			Date endDate, String status) {
		Sort sort = sortDir.equalsIgnoreCase(Sort.Direction.ASC.name()) ? Sort.by(sortField).ascending()
				: Sort.by(sortField).descending();

		Pageable pageable = PageRequest.of(pageno - NumberConstants.ONE, NumberConstants.TEN, sort);

		Specification<DailyReport> dateSpec = generalSpecificationDailyAttendance.dateSpecification(startDate, endDate, ApplicationConstants.DATE);
		Specification<DailyReport> empIdSpec = generalSpecificationDailyAttendance.stringSpecification(employeeId, DailyAttendanceConstants.EMPLOYEE_ID);
		Specification<DailyReport> empNameSpec = generalSpecificationDailyAttendance.stringSpecification(employeeName, DailyAttendanceConstants.EMPLOYEE_NAME);
		Specification<DailyReport> deptSpec = generalSpecificationDailyAttendance.stringSpecification(department, DailyAttendanceConstants.DEPARTMENT);
		Specification<DailyReport> statusSpec = generalSpecificationDailyAttendance.stringSpecification(status, DailyAttendanceConstants.ATTENDANCE_STATUS);
		Page<DailyReport> page = dailyAttendanceRepository.findAll(statusSpec.and(dateSpec).and(empIdSpec)
				.and(empNameSpec).and(deptSpec), pageable);
		return page;
	}

	@Override
	public List<DailyReport> getAllDailyReport() {
		 return (List<DailyReport>) dailyAttendanceRepository.findAll();
	}
}